# Generated by Django 5.0 on 2023-12-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
